name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Start Minikube
        run: |
          minikube start
          kubectl config use-context minikube

      - name: Install Prometheus
        run: helm install prometheus prometheus --namespace=monitoring

      - name: Install Grafana
        run: helm install grafana grafana --namespace=monitoring
